
@startuml

class Examen
{
  date
  coefficient
}

class Enseignant
{
  nom
  prenom
}

class etudiant
{
  numEtu
  nom
  prenom
  date_de_naissance
}

class cour
{
  code
  titre
}

etudiant "1" --- "1" Examen
(etudiant, Examen) . notes

etudiant "1.*" --- "1.*" cour : suivre

Examen "1" --- "1" cour : conserner

cour "1.*" --- "1" Enseignant : enseigner

class note
{
  valeur
}

'----------------------------------


class Ordinateur_Portable

class clavier

Ordinateurs_Portable "0..1" --- "1" etudiant

@enduml
