
@startuml

class Examen
{
  date
  coefficient
}

class Enseignant
{
  nom
  prenom
}

class etudiant as "Etudiant"
{
  idnumEtu
  nom
  prenom
  date_de_naissance
}

class cour as "Cour"
{
  code
  titre
}

etudiant "1.*" --- "0.*" Examen
(etudiant, Examen) . note

etudiant "1.*" --- "0.*" cour : suivre

Examen --- "1" cour : conserner

cour "*" --- "1" Enseignant : enseigner

class note
{
  valeur
}

'----------------------------------


class Ordinateur_Portable
{
  prix
  valeur_actuelle
}

class clavier as "Clavier"
{
  TypeClavier type
}

class Type
{
}

Azerty --|> Type
Qwerty --|> Type

class touche as "Touche"

class propriétaire as "Proprietaire"

Ordinateur_Portable "0..1" --- "1" propriétaire : appartenir

Ordinateur_Portable " " --- "1" clavier : possède

clavier "1" --- "*" touche

clavier " " -- "1" Type

@enduml
