@startuml

usecase r as (Effectuer des reservation)


usecase res as (Reservation des\nsalles de cours)

usecase rem as(Reservation matériel\n pédagogique)

r<|---res
r<|-rem



usecase pla as (consulter le planning)


usecase rh as (Consulter le recapitulatif horaire\n par enseignant)
usecase rhE as (Editer le recapitulatif horaire\n par enseignant)

pla <- Etudiant

pla <|-- r : creer

rh <|-- pla : calculer

Enseignant -> r 
Enseignant -> rh 

EnseignantResponsable -> Enseignant

EnseignantResponsable --> rhE 

Enseignant ---> Etudiant

@enduml
